name: pull-request-gate

on:
  pull_request:
    branches: [ '*' ]

env:
  BUILD_VERSION: 0.1.${{github.run_number}}
  SLN_PATH: src/ShellRunner.sln
  TEST_PATH: src/TestApp/bin/Release/net6.0/TestApp.dll

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore $SLN_PATH

    - name: Build
      run: dotnet build $SLN_PATH 
           -c Release 
           --no-restore 
           -p:Version=$BUILD_VERSION

    - name: Upload ShellRunner Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BuildArtifacts
        path: src/**/bin/Release/**/*

  build-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: BuildArtifacts    
        
    - name: Test
      run: dotnet $TEST_PATH
    