name: pull-request-gate

on:
  pull_request:
    branches: [ '*' ]

env:
  BUILD_VERSION: 0.1.${{github.run_number}}
  SLN_PATH: src/ShellRunner.sln
  PROJECT_PATH: src/ShellRunner/ShellRunner.csproj
  PRE_RELEASE_ARTIFACTS: src/**/*.$BUILD_VERSION-alpha.nupkg
  TEST_ARTIFACTS: src/**/bin/**/*
  TEST_PATH: TestApp/bin/Release/net6.0/TestApp.dll

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore $SLN_PATH

    - name: Build
      run: dotnet build $SLN_PATH 
           -c Release 
           --no-restore 
           -p:Version=$BUILD_VERSION

    - name: Test-Pack
      run: dotnet pack $PROJECT_PATH
           -c Release
           --no-restore
           --no-build
           -p:PackageVersion=$BUILD_VERSION-alpha
           
    - name: Upload Test Nuget Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BuildArtifacts
        path: $PRE_RELEASE_ARTIFACTS
        if-no-files-found: error

    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: TestArtifacts
        path: $TEST_ARTIFACTS

  build-test:
    needs: build
    runs-on: ubuntu-latest

    steps:  
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: TestArtifacts
        
    - name: Test
      run: dotnet $TEST_PATH
    